version: '3.7'
services:
  flask_app:
    image: flask-app-image
    container_name: flask-app-container
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - mes-network
    depends_on:
      - db

  # Mobile API PHP-FPM Service
  mobile_api_fpm:
    build:
      context: ./rest_api
      dockerfile: Dockerfile
    image: mobile-api-image
    container_name: mobile-api-container
    restart: unless-stopped
    volumes:
      - ./rest_api:/var/www
    networks:
      - mes-network
    depends_on:
      - db

  # IoT API PHP-FPM Service
  iot_api_fpm:
    build:
      context: ./iot_api
      dockerfile: Dockerfile
    image: iot-api-image
    container_name: iot-api-container
    restart: unless-stopped
    volumes:
      - ./iot_api:/var/www
    networks:
      - mes-network
    depends_on:
      - db

  # Dashboard API PHP-FPM Service
  dashboard_api_fpm:
    build:
      context: ./dashboard_api
      dockerfile: Dockerfile
    image: dashboard-api-image
    container_name: dashboard-api-container
    restart: unless-stopped
    volumes:
      - ./dashboard_api:/var/www
    networks:
      - mes-network
    depends_on:
      - db

  # MySQL Database Service
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mes_db
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mes-network

  # Nginx for Mobile API
  mobile_api_nginx:
    image: nginx:alpine
    container_name: mobile-api-nginx
    restart: unless-stopped
    volumes:
      - ./rest_api/public:/var/www/public
      - ./rest_api/docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - mes-network
    depends_on:
      - mobile_api_fpm

  # Nginx for IoT API
  iot_api_nginx:
    image: nginx:alpine
    container_name: iot-api-nginx
    restart: unless-stopped
    volumes:
      - ./iot_api/public:/var/www/public
      - ./iot_api/docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - mes-network
    depends_on:
      - iot_api_fpm

  # Nginx for Dashboard API
  dashboard_api_nginx:
    image: nginx:alpine
    container_name: dashboard-api-nginx
    restart: unless-stopped
    volumes:
      - ./dashboard_api/public:/var/www/public
      - ./dashboard_api/docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - mes-network
    depends_on:
      - dashboard_api_fpm

  # PhpMyAdmin for MySQL Management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 8081:80
    networks:
      - mes-network

  # Reverse Proxy Nginx Service
  reverse_proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mes-network
    depends_on:
      - mobile_api_nginx
      - iot_api_nginx
      - dashboard_api_nginx

networks:
  mes-network:
    driver: bridge

volumes:
  mysql-data:
