version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: iot-api-image
    container_name: iot-api-container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mes-network
    command: ["php-fpm"]

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: mes_db
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/MySQL
    ports:
      - 3306:3306
    networks:
      - mes-network

  iot-nginx:
    image: nginx:alpine
    container_name: iot-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - mes-network
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 8080:80
    networks:
      - mes-network

networks:
  mes-network:
    driver: bridge

volumes:
  mysql-data:


