version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mobile-api-image
    container_name: mobile-api-container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mes-network

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mes_db
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - mes-network
  
  nginx:
    image: nginx:alpine
    container_name: php-api-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - mes-network

networks:
  mes-network:
    driver: bridge

