version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mobile-api-image
    container_name: mobile-api-container
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - mes-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mes_db
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql-data:/var/lib/MySQL
    networks:
      - mes-network

  nginx:
    image: nginx:alpine
    container_name: php-api-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./public:/var/www/public
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - mes-network
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PASSWORD: rootpass
    ports:
      - 8080:80
    networks:
      - mes-network

networks:
  mes-network:
    driver: bridge

volumes:
  mysql-data:
