version: "3.8"

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mytododb
    ports:
      - "3306:3306"
    networks:
      - my-network

  my-flask-app:
    image: flask-todo-app
    container_name: my-flask-app
    ports:
      - "5000:5000"
    networks:
      - my-network

networks:
  my-network:
