version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mytododb'
      MYSQL_ROOT_PASSWORD: 'rootpass'  # Set the root password here
    ports:
      - '3306:3306'

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
    command: flask run --host=0.0.0.0

